name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        run: echo "${{ secrets.TRELLO_ENV }}" > .env
      - name: Build the Docker image
        run: docker build --progress=plain -t vanthuy/trello-app .
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Push to docker hub
        run: docker push vanthuy/trello-app
